# Generated by Django 6.0 on 2025-12-14 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='house_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='core.houseplan'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='YouTube channel or video link (short or embed format)', null=True),
        ),
    ]
