# Generated by Django 6.0 on 2025-12-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_quote_house_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='General Inquiry', max_length=200),
        ),
    ]
