# Generated by Django 6.0 on 2025-12-14 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseplan',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Depth in meters', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='houseplan',
            name='garage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='houseplan',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='houseplan',
            name='pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='houseplan',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube video URL', null=True),
        ),
        migrations.AddField(
            model_name='houseplan',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in meters', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('house_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='core.houseplan')),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('house_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.houseplan')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('ground', 'Ground Floor'), ('first', 'First Floor'), ('second', 'Second Floor'), ('third', 'Third Floor'), ('fourth', 'Fourth Floor'), ('fifth', 'Fifth Floor'), ('sixth', 'Sixth Floor'), ('seventh', 'Seventh Floor'), ('other', 'Other')], default='ground', max_length=20)),
                ('floor_area', models.IntegerField()),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('lounges', models.IntegerField(default=0)),
                ('dining_areas', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Floor-specific notes or description', null=True)),
                ('order', models.IntegerField(default=0, help_text='Order to display floors')),
                ('house_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='core.houseplan')),
            ],
            options={
                'verbose_name': 'Floor',
                'verbose_name_plural': 'Floors',
                'ordering': ['order', 'level'],
                'unique_together': {('house_plan', 'level')},
            },
        ),
    ]
