# Generated by Django 6.0 on 2025-12-14 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_houseplan_depth_houseplan_garage_houseplan_is_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseplan',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary/thumbnail image', null=True, upload_to='plans/'),
        ),
        migrations.CreateModel(
            name='HousePlanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plans/')),
                ('title', models.CharField(blank=True, help_text='Image title or description', max_length=200, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order to display images')),
                ('house_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_images', to='core.houseplan')),
            ],
            options={
                'verbose_name': 'House Plan Image',
                'verbose_name_plural': 'House Plan Images',
                'ordering': ['order'],
            },
        ),
    ]
