# Generated by Django 6.0 on 2025-12-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_houseplan_image_houseplanimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseplan',
            name='is_best_selling',
            field=models.BooleanField(default=False, help_text="Show in 'Best-Selling Designs' section"),
        ),
        migrations.AlterField(
            model_name='houseplan',
            name='is_popular',
            field=models.BooleanField(default=False, help_text="Show in 'Popular House Plans' section"),
        ),
    ]
