# Generated by Django 6.0 on 2025-12-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_houseplan_is_best_selling_alter_houseplan_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseplan',
            name='display_on',
            field=models.CharField(choices=[('house-plans', 'House Plans Page'), ('built-homes', 'Built Homes Page')], default='house-plans', help_text='Choose where to display this house plan', max_length=20),
        ),
    ]
