# Generated by Django 6.0 on 2025-12-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_houseplan_display_on'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE core_houseplan DROP COLUMN IF EXISTS display_section;',
            reverse_sql='',
        ),
    ]
